name: Build Trigger from Freedom Repo

on:
  push:
    branches:
      - master 

#env:
  #Branch: "master"
  #Environment: "dev"

jobs:
  call-shared:
    #uses: azu-commercial-it/az-glbl-freedom-workflow/.github/workflows/build.yml@master
    uses: AbbasSoftlogic/Java2/.github/workflows/build.yml@master 
    with:
      #branch: ${{ env.Branch }}
      branch: "master"
      #environment: ${{ env.Environment }}
      #environment: "dev"
      #release_version: ${{ github.ref_name }}.${{ github.run_number }}
    secrets: inherit
